#
# Workflow: Build Release
#

# this is a placeholder workflow in the master branch
# actual workflow is in the 4.0.z branch for now
# but we need workflow_dispatch workflows do be defined in master

name: Build Release
on:

  push:
    branches:
      - 'release/*'
    tags:
      - 'v*'

  #workflow_dispatch:
  #  branches:
  #    - 'release/*'
  #  inputs:
  #    version:
  #      description: Copy version (eg "2.1.4") to trigger release. CAREFUL!
  #      required: false
  #      default: ""

jobs:

  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - name: Do Nothing
        shell: bash
        run: echo "Doing Nothing"
